### ISSUE TITLE
Add code style config to server dir

### ISSUE THREAD

**Issue by 7erra** [MANVSim/MANVSim#119]
autopep8 offers several options to [configure settings](https://pypi.org/project/autopep8/#configuration). We should add e.g. a pyproject.toml to enforce settings across users and run autopep8 on the project.

**Comment by YIllmann** [comment]
In PyCharm there is an .editorconfig allowed to overwrite the style settings. However the settings allow a detailed configuration via User Input. I would suggest to identify differences and then agree on a solution. Therefore we dont enforce major IDE changes.

References: 
https://www.jetbrains.com/help/pycharm/reformat-and-rearrange-code.html
https://www.jetbrains.com/help/pycharm/configuring-code-style.html#create-copy
