### ISSUE TITLE
Scenario Management

### ISSUE THREAD

**Issue by H1ghBre4k3r** [MANVSim/MANVSim#169]
In the frontend, we need a way for a scenario admin to create new and edit existing scenarios. 

For that, we need to create a new page, new API endpoints, a new user (and possible permission-checks?). 

- [x] General Design of Frontend
- [ ] #236
- [x] Backend Implementation

**Comment by YIllmann** [comment]
> Scenario Mangement refers per our definition to managing executions. "Scenario Administration" would probably be a more fitting title, see [here](https://github.com/MANVSim/MANVSim/blob/main/doc/server/Architecture%20Backend%20Components.svg).

I can’t agree on this. The scenario management component is not equal to the execution management, as shown in your referenced docu. The former has no interface to the mobile api. The latter is the implementation you have worked on in the past weeks. All related to creating organizing an execution. Scenario Management defines the component, implementing the creation and editing of our templates.
