### ISSUE TITLE
Sublocations missing in location/all

### ISSUE THREAD

**Issue by lukas0820** [MANVSim/MANVSim#237]
I am currently testing the Location overview in the app and have an issue with the location/all endpoint.

To test, I am using the data from server/execution/tests/entities/dummy_entities.py. Based on the code, I understand that Location 1 ("RTW") should have several subLocations. However, when I call the {{baseUrl}}/run/location/all endpoint, either via the client or through Postman, the subLocations are empty for all locations in the response.

**Comment by lukas0820** [comment]
`{
    "locations": [
        {
            "id": 1,
            "media_references": [
                {
                    "media_reference": "media/static/image/rtw_sh.png",
                    "media_type": "IMAGE",
                    "text": null,
                    "title": null
                }
            ],
            "name": "RTW",
            "resources": [
                {
                    "id": 3,
                    "media_references": [
                        {
                            "media_reference": "media/static/image/no_image.png",
                            "media_type": "IMAGE",
                            "text": null,
                            "title": null
                        }
                    ],
                    "name": "Trage",
                    "quantity": 4
                }
            ],
            "sub_locations": []
        },
        {
            "id": 2,
            "media_references": [
                {
                    "media_reference": "media/static/image/rucksack_rot.jpg",
                    "media_type": "IMAGE",
                    "text": null,
                    "title": null
                }
            ],
            "name": "Roter Rucksack",
            "resources": [
                {
                    "id": 2,
                    "media_references": [
                        {
                            "media_reference": "media/static/image/no_image.png",
                            "media_type": "IMAGE",
                            "text": null,
                            "title": null
                        }
                    ],
                    "name": "Infusion",
                    "quantity": 3
                },
                {
                    "id": 4,
                    "media_references": [
                        {
                            "media_reference": "media/static/image/no_image.png",
                            "media_type": "IMAGE",
                            "text": null,
                            "title": null
                        }
                    ],
                    "name": "Blümchenpflaster",
                    "quantity": 10000
                }
            ],
            "sub_locations": []
        },
        {
            "id": 3,
            "media_references": [
                {
                    "media_reference": "media/static/image/rucksack_blau.jpg",
                    "media_type": "IMAGE",
                    "text": null,
                    "title": null
                }
            ],
            "name": "Blauer Rucksack",
            "resources": [
                {
                    "id": 5,
                    "media_references": [
                        {
                            "media_reference": "media/static/image/no_image.png",
                            "media_type": "IMAGE",
                            "text": null,
                            "title": null
                        }
                    ],
                    "name": "Beatmungsgerät",
                    "quantity": 1
                }
            ],
            "sub_locations": []
        },
        {
            "id": 4,
            "media_references": [
                {
                    "media_reference": "media/static/image/tasche_ekg.jpg",
                    "media_type": "IMAGE",
                    "text": null,
                    "title": null
                }
            ],
            "name": "EKG",
            "resources": [
                {
                    "id": 1,
                    "media_references": [
                        {
                            "media_reference": "media/static/image/no_image.png",
                            "media_type": "IMAGE",
                            "text": null,
                            "title": null
                        }
                    ],
                    "name": "EKG",
                    "quantity": 1
                }
            ],
            "sub_locations": []
        },
        {
            "id": 5,
            "media_references": [
                {
                    "media_reference": "media/static/image/no_image.png",
                    "media_type": "IMAGE",
                    "text": null,
                    "title": null
                }
            ],
            "name": "Holstein Stadion",
            "resources": [],
            "sub_locations": []
        }
    ]
}`

**Comment by simohlsen** [comment]
The `to_dict` and `to_json` methods of the Location-entity work as intended. Could be a mutation issue here in the `list()` function:
```python
return {
            "locations": [location.to_dict() for location
                          in list(execution.scenario.locations.values())]
        }
```

**Comment by YIllmann** [comment]
Das ist tendenziell spannend, weil sowohl in meinem Test und in Postman ist alles da.

Unit Test: ![image](https://github.com/user-attachments/assets/0238d9de-cb73-4b1b-900c-bf65209dcb0d)

eingeloggt als: 
![image](https://github.com/user-attachments/assets/06b10320-b340-432a-b105-da8fbe5f064d)
mit Anfrage auf location/all wie hier: 
![image](https://github.com/user-attachments/assets/2809d3f7-279d-4371-8884-17089805447a)

```{
    "locations": [
        {
            "id": 1,
            "media_references": [ ... ],
            "name": "RTW",
            "resources": [
                {
                    "id": 3,
                    "media_references": [ ... ],
                    "name": "Trage",
                    "quantity": 4
                }
            ],
            "sub_locations": [
                {
                    "id": 4,
                    "media_references": [ ... ],
                    "name": "EKG",
                    "resources": [
                        {
                            "id": 1,
                            "media_references": [...],
                            "name": "EKG",
                            "quantity": 1
                        }
                    ],
                    "sub_locations": []
                },
                {
                    "id": 3,
                    "media_references": [...],
                    "name": "Blauer Rucksack",
                    "resources": [
                        {
                            "id": 5,
                            "media_references": [...],
                            "name": "Beatmungsgerät",
                            "quantity": 1
                        }
                    ],
                    "sub_locations": []
                },
                {
                    "id": 2,
                    "media_references": [...],
                    "name": "Roter Rucksack",
                    "resources": [
                        {
                            "id": 2,
                            "media_references": [...],
                            "name": "Infusion",
                            "quantity": 3
                        },
                        {
                            "id": 4,
                            "media_references": [...],
                            "name": "Blümchenpflaster",
                            "quantity": 10000
                        }
                    ],
                    "sub_locations": []
                }
            ]
        },
        {
            "id": 2,
            "media_references": [...],
            "name": "Roter Rucksack",
            "resources": [
                {
                    "id": 2,
                    "media_references": [...],
                    "name": "Infusion",
                    "quantity": 3
                },
                {
                    "id": 4,
                    "media_references": [...],
                    "name": "Blümchenpflaster",
                    "quantity": 10000
                }
            ],
            "sub_locations": []
        },
        {
            "id": 3,
            "media_references": [...],
            "name": "Blauer Rucksack",
            "resources": [
                {
                    "id": 5,
                    "media_references": [...],
                    "name": "Beatmungsgerät",
                    "quantity": 1
                }
            ],
            "sub_locations": []
        },
        {
            "id": 4,
            "media_references": [...],
            "name": "EKG",
            "resources": [
                {
                    "id": 1,
                    "media_references": [...],
                    "name": "EKG",
                    "quantity": 1
                }
            ],
            "sub_locations": []
        },
        {
            "id": 5,
            "media_references": [...],
            "name": "Holstein Stadion",
            "resources": [],
            "sub_locations": []
        }
    ]
}```

Gib mir gerne mal bitte den zugehörigen Branch, dann kann ich das da nochmal testen.

**Comment by lukas0820** [comment]
Vielleicht ist hier das Problem, dass die Locations mehrfach zugeordnet werden:
SIe werden sowohl als Top Level Location verwendet, als auch als Sub Location von RTW und befinden sich ebenfalls im Inventar des Spielers '987ZYX'.

Zum testen verwende ich gerade branch 'feature/app/238-app-implement-patient-move-action'.
Ich konnte gerade auch dein Ergebnis nach einem Neustart reproduzieren , sobald ich allerdings einmal location/leave aufrufe, sind die Sublocations wieder leer. Es scheint so, als würden sie vorher nur angeigt werden, da sich der Spieler an der Location befundet und diese im Inverntar hat

**Comment by YIllmann** [comment]
Das Inventar ist tatsächlich ausschlaggebend. Wenn ein Spieler die Sublocations in seinem Inventar behält, werden diese an den Spieler gebunden. Das heißt, sobald der Spieler eine Location verlässt, nimmt er sein Inventar mit, es sei denn er legt aktiv eine location über das put ab. Tendenziell hast du mit dem "Problem" gezeigt, dass das Inventar Management bei Leave Location einwandfrei funktioniet :D. Auch wenn es nicht deine Absicht war.
