### ISSUE TITLE
Put-to Endpoint: Location Assignment Required, Duplication of Locations

### ISSUE THREAD

**Issue by lukas0820** [MANVSim/MANVSim#254]
I am currently testing the `/run/location/put-to` endpoint and have some issues with it

## Does not work when player not assigned to any location

The endpoint only works if a Player is assigned to a Location, and this only occurs when the Player is at a Patient Location (as there is no possibility to arrive at a top level location). However, to access the Location overview, the Player needs to close the Patient overview in the Client app which leads to leaving the Patient and becoming unassigned to any Location.

For example this request (location 2 is in the players inventory and location 5 is a top level location)

```
{
  "put_location_ids": "[2]",
  "to_location_ids": "[5]"
}
```
results in 
```
404: Put-Location not found. Update your current location-access
```

## Duplication of Locations

The Location is not moved from the inventory to the specified Location but rather copied. It is not removed from the Player's inventory.
This was tested when the player was initially assigned to top-level Location 1. The following request was used:

```
{
  "put_location_ids": "[1, 2]",
  "to_location_ids": "[5]"
}
```

Result of `/run/location/all`:

```
{
            "id": 5,
            "media_references": [
                {
                    "media_reference": "media/static/image/no_image.png",
                    "media_type": "IMAGE",
                    "text": null,
                    "title": null
                }
            ],
            "name": "Holstein Stadion",
            "resources": [],
            "sub_locations": [
                {
                    "id": 2,
                    "media_references": [
                        {
                            "media_reference": "media/static/image/rucksack_rot.jpg",
                            "media_type": "IMAGE",
                            "text": null,
                            "title": null
                        }
                    ],
                    "name": "Roter Rucksack",

```

Result of `/run/player/inventory`:

```
{
    "accessible_locations": [
        {
            "id": 2,
            "media_references": [
                {
                    "media_reference": "media/static/image/rucksack_rot.jpg",
                    "media_type": "IMAGE",
                    "text": null,
                    "title": null
                }
            ],
            "name": "Roter Rucksack",
```

## Not possible for resources

It seems that it is not possible to put or take resources. However, there are resources at top-level Locations, which means such resources cannot be used. For example, here is an "RTW" top-level Location with the resource "Trage."

        {
            "id": 1,
            "media_references": [
                {
                    "media_reference": "media/static/image/rtw_sh.png",
                    "media_type": "IMAGE",
                    "text": null,
                    "title": null
                }
            ],
            "name": "RTW",
            "resources": [
                {
                    "id": 3,
                    "media_references": [
                        {
                            "media_reference": "media/static/image/no_image.png",
                            "media_type": "IMAGE",
                            "text": null,
                            "title": null
                        }
                    ],
                    "name": "Trage",
                    "quantity": 4
                }
            ],
            "sub_locations": []
        },

**Comment by YIllmann** [comment]
1) The methods are not designed for players standing in empty space. However if you designed your app that way, i need to apply some changes to fix the bug. I will open an Issue for it.

2) needs further research, but should be fixable

3) results from a test-data failure. A location that a vehicle should store resources. However our db design allows such data constellation. There are a few fixes for that but due to time limits this should be marked as future work an limit of the application.

**Comment by simohlsen** [comment]
> A vehicle-location should not store resources

Why not? How do you model something like additional medicine only available _in_ the RTW?

**Comment by YIllmann** [comment]
> > A vehicle-location should not store resources
> 
> Why not? How do you model something like additional medicine only available _in_ the RTW?

never talked about it, never realized it. In your example data you defined an EKG as resource as well as a location. That was the implementation standard i used for the API design. Never worked with this case before.

**Comment by lukas0820** [comment]
> 
> never talked about it, never realized it. In your example data you defined an EKG as resource as well as a location. That was the implementation standard i used for the API design. Never worked with this case before.

For the following example with 'RTW' and the resource 'Trage' (quantity 4) this means that there should be 4 locations instead to be able to take a single one, is this correct?
```
        "resources": [
            {
                "id": 3,
                "media_references": [
                    {
                        "media_reference": "media/static/image/no_image.png",
                        "media_type": "IMAGE",
                        "text": null,
                        "title": null
                    }
                ],
                "name": "Trage",
                "quantity": 4
            }
```

**Comment by YIllmann** [comment]
> > never talked about it, never realized it. In your example data you defined an EKG as resource as well as a location. That was the implementation standard i used for the API design. Never worked with this case before.
> 
> For the following example with 'RTW' and the resource 'Trage' (quantity 4) this means that there should be 4 locations instead to be able to take a single one, is this correct?
> 
> ```
>         "resources": [
>             {
>                 "id": 3,
>                 "media_references": [
>                     {
>                         "media_reference": "media/static/image/no_image.png",
>                         "media_type": "IMAGE",
>                         "text": null,
>                         "title": null
>                     }
>                 ],
>                 "name": "Trage",
>                 "quantity": 4
>             }
> ```

That is correct. I would certainly agree, to implement resource put and take. But in this case that would mean to rework the inventory system. The inventory is location-based only. Therefore a resource needs to be stored into a location for a player to be accessible. In this case Trage won’t fit in any location because no Trage can be contained in a backpack for example. That’s why the game is limited in its current design. That’s a fact we won’t be able to change before September. Not with the resources we currently have. :)

**Comment by simohlsen** [comment]
> > > A vehicle-location should not store resources
> > 
> > 
> > Why not? How do you model something like additional medicine only available _in_ the RTW?
> 
> never talked about it, never realized it. In your example data you defined an EKG as resource as well as a location. That was the implementation standard i used for the API design. Never worked with this case before.

This is actually a requirement. As in the RTW there is more and other medicine than in the backpacks. Also oxygen and other stuff is only available *in* the RTW and cannot be moved away from there. The EKG is a special case as it is a location and resource at the same time but that is not generally the case. The "Trage" could be also modeled that way but the other stuff not, I think.

**Comment by YIllmann** [comment]
> > > > A vehicle-location should not store resources
> > > 
> > > 
> > > Why not? How do you model something like additional medicine only available _in_ the RTW?
> > 
> > 
> > never talked about it, never realized it. In your example data you defined an EKG as resource as well as a location. That was the implementation standard i used for the API design. Never worked with this case before.
> 
> This is actually a requirement. 

Du to the changes in the priority, i will further investigate our possibilities. I would be possible design a way to take resources along with the player. I would like to talk about some ideas when I return from vacation :)

**Comment by lukas0820** [comment]
1 and 2 are fixed
3 has a new issue here: #266
