### ISSUE TITLE
204 no content on /patient/all-ids

### ISSUE THREAD

**Issue by n00on** [MANVSim/MANVSim#281]
When logging in with `123ABC` and navigating to the patientlist `204 No Content` is returned instead of an empty list or an error.

I couldn't figure out why. Unstarted execution? No patients? Either way this doesn't seem like intended behaviour.

**Comment by simohlsen** [comment]
Did you start the server with `LOAD_TEST_DATA` set to `true` ? The player `123ABC` is part of an execution that is only loaded when that flag is set.

**Comment by n00on** [comment]
> Did you start the server with `LOAD_TEST_DATA` set to `true` ? The player `123ABC` is part of an execution that is only loaded when that flag is set.

Yes, the Login was successfull, the Error was after that in the patientlist Page when calling the enpoint all-ids.

**Comment by simohlsen** [comment]
Don't know whether it's related to that, but do you really expect data with a key `tans`?
```
return {
            "tans": list(execution.scenario.patients.keys())
        }
```
I am a bit surprised to see this as only players have TANs as IDs.

**Comment by lukas0820** [comment]
The test data includes two different executions:

- Execution 1: This execution contains players with TANs "123ABC" and "456DEF." The status is currently pending, and there is no start time recorded.
- Execution 2: This execution contains players with TANs "987ZYX" and "654WVU." The status is running

For Execution 1, the status is pending, and no start time is set. @n00on, did you skip the wait screen during your tests? If so, it doesn't seem like unintended behavior to me to return a 204 HTTP error code, as the execution hasn't started yet. In a production environment, players should never be able to bypass the wait screen, so this scenario would not occur.

**Comment by YIllmann** [comment]
every url on '/api/run' is routed through a [filter](https://github.com/MANVSim/MANVSim/blob/main/server/execution/api/setup.py) that checks if the execution is in a running state. If not 204 indicates a succesful request on the execution. However the players are not allowed to perform game actions.

**Comment by n00on** [comment]
I did indeed bypass the waiting screen.  
I'd have expected an error if i access something I shouldn't be doing.  
But I guess `204 NO CONTENT` also makes sense, as there is no active execution, so no content.  

> Don't know whether it's related to that, but do you really expect data with a key `tans`?

I also noticed it and changed it to `patient_ids` in #275 @simohlsen
