### ISSUE TITLE
Login to web interface from deployed instance not possible

### ISSUE THREAD

**Issue by simohlsen** [MANVSim/MANVSim#286]
Investigate the login issues on the server with the default credentials (see Mattermost).

**Comment by n00on** [comment]
Now the dbsetup.py is executed in the setup.sh, so the webusers are available in the deployed instance.  
However there seem to be substantial issues with the CSRF setup.  
I get errors `400 BAD REQUEST` with `{"error":"The CSRF session token is missing."}` or `422 UNPROCESSABLE ENTITY` with `{"msg":"Signature verification failed"}`.  
![image](https://github.com/user-attachments/assets/38b27036-f1fa-4bb3-989a-6090a5af53f9)  
This seems to happen randomly as sometimes I'm able to log in, just to be logged out in one of the following requests. Also the CSRF token is missing error happens even though the request payload contains the csrf_token as `multipart/form-data`.  
![image](https://github.com/user-attachments/assets/9a988804-0e69-4b88-b722-f93355718b08)  
I tried it on Firefox and Chrome and running the flask app in debug mode or served through gunicorn. I used `docker-compose.yaml` to start the services.  
Maybe the error is with the csrf setup in the flask app or in the react app?

**Comment by n00on** [comment]
I've found the error:  
In docker compose the flask server was served using `gunicorn` using 4 workers. However as each worker generated their own `SECRET_KEY` one worker couldn't verify the CSRF token generated by another worker. Thus it seemed undeterministic wether a request was accepted or declined.  
I fixed it through having only one worker: https://github.com/MANVSim/MANVSim/pull/288  

However if we need more workers/performance in the future we might have to think of a way to share the SECRET_KEY across workers, maybe through the DB? @simohlsen

**Comment by simohlsen** [comment]
@n00on Good job! I think for now one worker is fine, as there is not that much traffic on the website - probably at most one or two persons at a time. But we should definitely keep that in mind! I'll write a new issue for that, but we probably won't have to address it for now.

**Comment by simohlsen** [comment]
See #289
