### ISSUE TITLE
Different TAN Length

### ISSUE THREAD

**Issue by lukas0820** [MANVSim/MANVSim#295]
In the Flutter app and server test data, TANs are used with a length of 6 characters, while the React frontend currently generates TANs with a length of 5. Since the app requires users to input TANs of the expected length, the mismatch prevents the generated TANs from being used.

To resolve this, we need to standardize the TAN length across flutter app, react app and server

**Comment by lukas0820** [comment]
The changes in the app would be minimal (just a constant change), but on the server, adjusting the length would require updating the test data and the corresponding tests.

**Comment by YIllmann** [comment]
FYI in the file [tans](server/utils/tans.py)the length is per default a length of 5. However, this parameter can vary. What exactly causes the problem on the client? How do you deal with the situation, that the tans length are incremented due to lack of possibilities?

**Comment by lukas0820** [comment]
Our TAN input accepts a predefined number of characters:

![grafik](https://github.com/user-attachments/assets/2fbb465a-630b-4b8f-8a11-96a9aa4fab08)

However, it’s not a problem to change it to 5. If we do, we will need to adapt the [server's test data](https://github.com/MANVSim/MANVSim/blob/main/server/execution/tests/entities/dummy_entities.py)

**Comment by YIllmann** [comment]
Why do you limit the amount of characters for the TAN, if the server allows TANs of undefined length? I think a basic input field would be more fitting and resolves the issue. Further the Player should be forced to use the QR Code and use the TAN input only as a secondary method. What do you think?
