### ISSUE TITLE
Change debug level to INFO

### ISSUE THREAD

**Issue by 7erra** [MANVSim/MANVSim#302]
IMO the DEBUG setting provides too much information such as file system accesses. Instead we should use the INFO level to only get relevant information such as status codes.

**Comment by YIllmann** [comment]
IMO as long as we implement debug is a nice to have. Depending on the Deployment it can be possible to set the debug level via env vars. Then we need to add an ENVVAR for the gh-action and change it to the desired level locally for ourself.
