### ISSUE TITLE
Patient IDs broken

### ISSUE THREAD

**Issue by lukas0820** [MANVSim/MANVSim#341]
Something seems to be wrong with the patient IDs. When I query all of them with `/run/patient/all-ids`, I get this list of IDs:

```
{
    "patient_ids": [
        3,
        4,
        1,
        2
    ],
}
```

Then i call `/run/patient/arrive` and the ID changes in the response

Request:
```
{
  "patient_id": 1
}
```
Respsonse:
```
{
    "patient": {
        "classification": "NOT_CLASSIFIED",
        "id": 1726399745305,
```

With this new id requests to the action and move endpoints fail

I tested with player TAN `987ZYX` and the test data from 'Dummy Execution 2024 - zwei Wagen'

**Comment by YIllmann** [comment]
the current test-data seemed to be a little buggy  over the time. I would suggest to test again, after mergin, the updated setup. PR is pending.
